package com.gymos.app.screens

import androidx.compose.animation.*
import androidx.compose.animation.core.*
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.material3.Text
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import kotlinx.coroutines.delay

val frases = listOf(
    Pair("El dolor que sentís hoy es la fuerza que vas a sentir mañana.", "Anónimo"),
    Pair("No se trata de ser el mejor. Se trata de ser mejor que ayer.", "Anónimo"),
    Pair("El cuerpo logra lo que la mente cree.", "Napoleon Hill"),
    Pair("Cada rep te acerca más a quien querés ser.", "Anónimo"),
    Pair("El único mal entrenamiento es el que no hiciste.", "Anónimo"),
    Pair("Tu único límite sos vos.", "Anónimo"),
    Pair("Sudá ahora, brilla después.", "Anónimo"),
    Pair("La disciplina es elegir entre lo que querés ahora y lo que más querés.", "Abraham Lincoln"),
    Pair("Levantate, trabajá duro, repetí.", "Anónimo"),
    Pair("El éxito no se logra solo con cualidades especiales. Es sobre todo un trabajo de constancia.", "Anónimo"),
    Pair("No pares cuando estés cansado. Pará cuando hayas terminado.", "Anónimo"),
    Pair("Cada gota de sudor es un paso más cerca de tu meta.", "Anónimo"),
    Pair("El gimnasio es el único lugar donde el dolor se convierte en progreso.", "Anónimo"),
    Pair("Si querés algo que nunca tuviste, tenés que hacer algo que nunca hiciste.", "Anónimo"),
    Pair("La fuerza no viene de ganar. Viene de luchar y decidir no rendirse.", "Arnold Schwarzenegger"),
    Pair("Primero hacelo posible, luego hacelo fácil, luego hacelo hermoso.", "Anónimo"),
    Pair("No hay atajos para ningún lugar que valga la pena ir.", "Beverly Sills"),
    Pair("El secreto está en empezar.", "Mark Twain"),
    Pair("Pequeños progresos son siempre progresos.", "Anónimo"),
    Pair("Tu cuerpo puede soportar casi cualquier cosa. Es tu mente la que tenés que convencer.", "Anónimo"),
    Pair("Los campeones no nacen en el gimnasio. Se hacen con lo que sienten dentro.", "Muhammad Ali"),
    Pair("No busques la perfección, buscá el progreso.", "Anónimo"),
    Pair("Un año de entrenamiento. Un año de diferencia.", "Anónimo"),
    Pair("Hacé hoy lo que otros no quieren hacer. Mañana tendrás lo que otros no pueden tener.", "Anónimo"),
    Pair("La motivación te arranca, el hábito te lleva.", "Jim Ryun"),
    Pair("Cada entrenamiento es un paso que te aleja de quien eras.", "Anónimo"),
    Pair("Cuando sientas que querés parar, recordá por qué empezaste.", "Anónimo"),
    Pair("La única persona que podés ser mejor que vos es la de ayer.", "Anónimo"),
    Pair("El esfuerzo de hoy es el resultado de mañana.", "Anónimo"),
    Pair("No te compares con nadie. Corré tu propia carrera.", "Anónimo"),
    Pair("El músculo se construye fuera de la zona de confort.", "Anónimo"),
    Pair("Cada kilómetro recorrido es una victoria sobre la pereza.", "Anónimo"),
    Pair("La consistencia vence al talento cuando el talento no es consistente.", "Anónimo"),
    Pair("Hacé que cada repetición cuente.", "Anónimo"),
    Pair("Tu cuerpo es un reflejo de tu estilo de vida.", "Anónimo"),
    Pair("No se trata de tener tiempo. Se trata de hacerlo.", "Anónimo"),
    Pair("El éxito empieza con la decisión de intentarlo.", "Anónimo"),
    Pair("El que no arriesga, no gana. El que no entrena, no cambia.", "Anónimo"),
    Pair("La grandeza no se regala. Se gana.", "Anónimo"),
    Pair("Un cuerpo fuerte construye una mente fuerte.", "Anónimo"),
    Pair("Soñaste con esto. Ahora trabajá por ello.", "Anónimo"),
    Pair("El sacrificio de hoy es el triunfo de mañana.", "Anónimo"),
    Pair("Entrenás cuando tenés ganas y también cuando no tenés ganas. Eso es disciplina.", "Anónimo"),
    Pair("La mejor inversión que podés hacer es en vos mismo.", "Warren Buffett"),
    Pair("Nunca es demasiado tarde para ser lo que podrías haber sido.", "George Eliot"),
    Pair("Creé en vos mismo y todo lo demás viene solo.", "Anónimo"),
    Pair("El dolor es temporal. El orgullo es para siempre.", "Anónimo"),
    Pair("No te rindas. Los comienzos siempre son difíciles.", "Anónimo"),
    Pair("Lo que hacés hoy puede mejorar todos tus mañanas.", "Ralph Marston"),
    Pair("La dedicación es lo que separa a los que sueñan de los que logran.", "Anónimo"),
    Pair("Cada vez que entrenás, le ganás a la versión de vos que quería quedarse en casa.", "Anónimo"),
    Pair("No importa lo lento que vayas, siempre y cuando no te detengas.", "Confucio"),
    Pair("El trabajo duro supera al talento cuando el talento no trabaja duro.", "Tim Notke"),
    Pair("Hacé que tu entrenamiento sea tu terapia.", "Anónimo"),
    Pair("Cada mañana que entrenás es una victoria antes del amanecer.", "Anónimo"),
    Pair("El éxito es la suma de pequeños esfuerzos repetidos día tras día.", "Robert Collier"),
    Pair("Si no te duele, no cambia. Si no cambia, ¿para qué lo hacés?", "Anónimo"),
    Pair("El verdadero desafío no es levantar el peso. Es levantarte vos.", "Anónimo"),
    Pair("Sé la persona que tu yo del futuro va a agradecer.", "Anónimo"),
    Pair("La fuerza viene de creer que podés.", "Anónimo"),
    Pair("Hoy es un buen día para ser mejor.", "Anónimo"),
    Pair("No hay excusas en el camino al éxito.", "Anónimo"),
    Pair("Un entrenamiento a la vez. Un día a la vez.", "Anónimo"),
    Pair("Tu mente se rinde antes que tu cuerpo. No la escuches.", "Anónimo"),
    Pair("La constancia construye imperios.", "Anónimo"),
    Pair("Vas a agradecer haberte esforzado.", "Anónimo"),
    Pair("Los resultados llegan a quienes no paran.", "Anónimo"),
    Pair("Cada vez que entrenás, tu cuerpo dice gracias.", "Anónimo"),
    Pair("No busques motivación, construí hábitos.", "Anónimo"),
    Pair("El camino al éxito está pavimentado de sudor.", "Anónimo"),
    Pair("Entrenás con lo que tenés para obtener lo que querés.", "Anónimo"),
    Pair("La diferencia entre ordinario y extraordinario es ese pequeño extra.", "Jimmy Johnson"),
    Pair("Empezá donde estás. Usá lo que tenés. Hacé lo que podés.", "Arthur Ashe"),
    Pair("Si querés cambiar tu cuerpo, primero cambiá tu mentalidad.", "Anónimo"),
    Pair("El gym no te pide que seas perfecto. Te pide que aparezcas.", "Anónimo"),
    Pair("Cada peso que levantás te hace más fuerte que ayer.", "Anónimo"),
    Pair("Nadie logró nada grande sin esfuerzo.", "Anónimo"),
    Pair("El progreso requiere paciencia y dedicación.", "Anónimo"),
    Pair("Hoy podés elegir ser mejor. Elegí bien.", "Anónimo"),
    Pair("No te enfoques en el resultado. Enfocate en el proceso.", "Anónimo"),
    Pair("La disciplina es la puente entre tus metas y tus logros.", "Jim Rohn"),
    Pair("El gym es donde las excusas van a morir.", "Anónimo"),
    Pair("Vos sabés que podés. Ahora demostrátelo.", "Anónimo"),
    Pair("El cuerpo que querés se construye con las decisiones de hoy.", "Anónimo"),
    Pair("Sé más fuerte que tus excusas.", "Anónimo"),
    Pair("No hay éxito sin sacrificio.", "Anónimo"),
    Pair("Transformate en la persona que te inspira.", "Anónimo"),
    Pair("Cuando dudes, seguí adelante.", "Anónimo"),
    Pair("Los límites son solo el comienzo de algo grande.", "Anónimo"),
    Pair("El músculo no distingue entre excusas y esfuerzo. Solo responde al esfuerzo.", "Anónimo"),
    Pair("Cada entrenamiento es una promesa que te cumplís a vos mismo.", "Anónimo"),
    Pair("No esperes el momento perfecto. Hacé el momento perfecto.", "Anónimo"),
    Pair("La victoria pertenece a los más perseverantes.", "Napoleón Bonaparte"),
    Pair("Sé tu propia motivación.", "Anónimo"),
    Pair("El esfuerzo nunca miente.", "Anónimo"),
    Pair("Cada día es una nueva oportunidad para mejorar.", "Anónimo"),
    Pair("Levantate más fuerte de lo que caíste.", "Anónimo"),
    Pair("No es fácil. Por eso vale la pena.", "Anónimo"),
    Pair("Tu futuro yo te va a agradecer cada entrenamiento.", "Anónimo"),
    Pair("No pares. Cada paso importa.", "Anónimo"),
    Pair("La mente fuerte mueve cuerpos fuertes.", "Anónimo"),
    Pair("El fitness es un viaje, no un destino.", "Anónimo"),
    Pair("Hace falta valentía para empezar y carácter para continuar.", "Anónimo"),
    Pair("Rendirte nunca va a ser tu mejor opción.", "Anónimo"),
    Pair("Transformá el esfuerzo en resultados.", "Anónimo"),
    Pair("Cada kilo levantado cuenta una historia de esfuerzo.", "Anónimo"),
    Pair("Cuando el cuerpo dice basta, la mente dice uno más.", "Anónimo"),
    Pair("El éxito es una decisión que se toma todos los días.", "Anónimo"),
    Pair("Sé imparable.", "Anónimo"),
    Pair("Entrenar es el idioma universal del esfuerzo.", "Anónimo"),
    Pair("Cada gota de sudor vale el doble en resultados.", "Anónimo"),
    Pair("El que entrena hoy, gana mañana.", "Anónimo"),
    Pair("No dejes para mañana el entrenamiento que podés hacer hoy.", "Anónimo"),
    Pair("La transformación comienza con una decisión.", "Anónimo"),
    Pair("Sé constante y los resultados llegarán.", "Anónimo"),
    Pair("La fuerza de voluntad es el músculo más importante.", "Anónimo"),
    Pair("No te compares con los demás. Comparate con quien eras ayer.", "Anónimo"),
    Pair("El entrenamiento de hoy es la energía de mañana.", "Anónimo"),
    Pair("Hacé el trabajo aunque no tengas ganas.", "Anónimo"),
    Pair("El que persiste, triunfa.", "Anónimo"),
    Pair("Cada sesión de entrenamiento es un ladrillo en el edificio de tu éxito.", "Anónimo"),
    Pair("No hay atajos para ponerse en forma. Solo trabajo.", "Anónimo"),
    Pair("Empezar es la mitad del camino.", "Anónimo"),
    Pair("Tu cuerpo escucha todo lo que tu mente dice.", "Anónimo"),
    Pair("Sé el atleta de tu propia vida.", "Anónimo"),
    Pair("El éxito está reservado para los que no aceptan el fracaso como opción.", "Anónimo"),
    Pair("Más fuerte de lo que pensás. Más capaz de lo que creés.", "Anónimo"),
    Pair("No busques inspiración. Sé la inspiración.", "Anónimo"),
    Pair("El cuerpo necesita ser desafiado para crecer.", "Anónimo"),
    Pair("Cada rep es una victoria.", "Anónimo"),
    Pair("Los resultados hablan más fuerte que las palabras.", "Anónimo"),
    Pair("Entrená como si tu vida dependiera de ello.", "Anónimo"),
    Pair("La mente que no se rinde crea el cuerpo que no para.", "Anónimo"),
    Pair("Hoy más fuerte que ayer, mañana más fuerte que hoy.", "Anónimo"),
    Pair("Sé el cambio que querés ver en tu cuerpo.", "Anónimo"),
    Pair("No es el gym el que te cambia. Sos vos.", "Anónimo"),
    Pair("Cuando duela, acordate del objetivo.", "Anónimo"),
    Pair("El verdadero progreso está fuera de la zona de confort.", "Anónimo"),
    Pair("No necesitás ser rápido. Solo necesitás no parar.", "Anónimo"),
    Pair("Convertí tu 'quiero' en 'voy a'.", "Anónimo"),
    Pair("El fitness empieza en la cabeza.", "Anónimo"),
    Pair("La mejor versión de vos está a un entrenamiento de distancia.", "Anónimo"),
    Pair("Entrená duro, recuperate bien, repetí.", "Anónimo"),
    Pair("El que no arriesga músculos, no gana músculos.", "Anónimo"),
    Pair("Cada entrenamiento te hace invencible.", "Anónimo"),
    Pair("No hay excusa que valga más que tu salud.", "Anónimo"),
    Pair("La vida es más fácil cuando estás en forma.", "Anónimo"),
    Pair("Sé disciplinado cuando la motivación desaparezca.", "Anónimo"),
    Pair("El camino más largo empieza con un solo paso.", "Lao Tzu"),
    Pair("El que tiene un porqué aguanta cualquier cómo.", "Friedrich Nietzsche"),
    Pair("Hacé del esfuerzo tu zona de confort.", "Anónimo"),
    Pair("Tus metas no se van a lograr solas.", "Anónimo"),
    Pair("Si podés soñarlo, podés lograrlo.", "Walt Disney"),
    Pair("No hay mejor sensación que terminar un entrenamiento duro.", "Anónimo"),
    Pair("Entrenás para vos. Nadie más.", "Anónimo"),
    Pair("El dolor es debilidad abandonando el cuerpo.", "Anónimo"),
    Pair("Cada entrenamiento es un regalo que te das a vos mismo.", "Anónimo"),
    Pair("Apostá por vos mismo siempre.", "Anónimo"),
    Pair("No hay meta inalcanzable con suficiente esfuerzo.", "Anónimo"),
    Pair("Que tu entrenamiento sea tan fuerte como tus metas.", "Anónimo"),
    Pair("El sudor de hoy es el brillo de mañana.", "Anónimo"),
    Pair("Un entrenamiento intenso vale más que mil días de dudas.", "Anónimo"),
    Pair("Hacete cargo de tu cuerpo. Nadie más lo va a hacer.", "Anónimo"),
    Pair("La rutina correcta cambia vidas.", "Anónimo"),
    Pair("Sé más fuerte que tus pensamientos negativos.", "Anónimo"),
    Pair("Cada serie completada es una promesa cumplida.", "Anónimo"),
    Pair("El que entrena con propósito llega más lejos.", "Anónimo"),
    Pair("Tus hábitos construyen tu destino.", "Anónimo"),
    Pair("El progreso es progreso, sin importar el tamaño.", "Anónimo"),
    Pair("No te subestimes. El potencial que tenés es enorme.", "Anónimo"),
    Pair("Sé el tipo de persona que termina lo que empieza.", "Anónimo"),
    Pair("Cada día que entrenás es un día ganado.", "Anónimo"),
    Pair("Lo que el ojo no ve, el músculo lo siente.", "Anónimo"),
    Pair("La perseverancia es el motor del cambio.", "Anónimo"),
    Pair("Entrenar no es un castigo. Es un privilegio.", "Anónimo"),
    Pair("La energía que gastás en el gym la recuperás el doble en la vida.", "Anónimo"),
    Pair("Hacé de tu entrenamiento una celebración de lo que tu cuerpo puede hacer.", "Anónimo"),
    Pair("No busques ser perfecto. Buscá ser consistente.", "Anónimo"),
    Pair("Cada minuto de entrenamiento vale más que una hora de arrepentimiento.", "Anónimo"),
    Pair("Los grandes logros requieren grandes esfuerzos.", "Anónimo"),
    Pair("El mejor proyecto en el que podés trabajar sos vos mismo.", "Anónimo"),
    Pair("Sé el ejemplo que te gustaría ver.", "Anónimo"),
    Pair("El esfuerzo de hoy se convierte en el orgullo de mañana.", "Anónimo"),
    Pair("Construí el cuerpo que te merece la vida que querés.", "Anónimo"),
    Pair("Cada entrenamiento es un paso hacia la mejor versión de vos.", "Anónimo"),
    Pair("No des excusas. Da resultados.", "Anónimo"),
    Pair("El músculo que más importa es el corazón.", "Anónimo"),
    Pair("Confía en el proceso aunque no veas los resultados todavía.", "Anónimo"),
    Pair("Lo difícil se hace. Lo imposible también.", "Anónimo"),
    Pair("No hay límites, solo barreras que superar.", "Anónimo"),
    Pair("Si tu cuerpo puede, tu mente no tiene excusas.", "Anónimo"),
    Pair("Cada mañana es una nueva oportunidad de ser mejor.", "Anónimo"),
    Pair("El trabajo duro siempre da sus frutos.", "Anónimo"),
    Pair("No te rindas cuando estés cansado. Rendite cuando hayas terminado.", "Anónimo"),
    Pair("Ser fuerte no es opcional. Es necesario.", "Anónimo"),
    Pair("Sé implacable con tus metas.", "Anónimo"),
    Pair("La fuerza no es sobre el peso que levantás. Es sobre el peso que no te aplasta.", "Anónimo"),
    Pair("Hoy tenés la oportunidad de ser quien querés ser. Aprovechala.", "Anónimo"),
    Pair("El camino es duro, pero el destino vale la pena.", "Anónimo"),
    Pair("Si ya empezaste, no pares. Si no empezaste, hoy es el día.", "Anónimo"),
    Pair("El tiempo pasa de todas formas. Mejor que pase entrenando.", "Anónimo"),
    Pair("Sé el guerrero que hay dentro de vos.", "Anónimo"),
    Pair("Tus metas no te esperan. Vos tenés que ir a buscarlas.", "Anónimo"),
    Pair("No existe el 'mañana empiezo' en el diccionario del éxito.", "Anónimo"),
    Pair("La constancia es el secreto que nadie quiere escuchar.", "Anónimo"),
    Pair("Un cuerpo en movimiento tiende a seguir en movimiento.", "Isaac Newton"),
    Pair("Sé más grande que tus miedos.", "Anónimo"),
    Pair("Cada entrenamiento es una victoria sobre la pereza.", "Anónimo"),
    Pair("Si no te desafías, no cambiás.", "Anónimo"),
    Pair("Trabajá en silencio. Que los resultados hagan el ruido.", "Anónimo"),
    Pair("El gym es el lugar donde los sueños se vuelven músculos.", "Anónimo"),
    Pair("No hay nada que un buen entrenamiento no mejore.", "Anónimo"),
    Pair("El primer paso siempre es el más difícil. Ya lo diste.", "Anónimo"),
    Pair("Construí tu físico como construís tu carácter: con esfuerzo diario.", "Anónimo"),
    Pair("La mente decide, el cuerpo ejecuta.", "Anónimo"),
    Pair("Sé apasionado con tus metas y paciente con tu progreso.", "Anónimo"),
    Pair("No importa el ritmo, importa no parar.", "Anónimo"),
    Pair("Entrená tu cuerpo. Fortalecé tu mente.", "Anónimo"),
    Pair("Los que no se rinden son los que llegan.", "Anónimo"),
    Pair("Hacé del movimiento tu medicina.", "Anónimo"),
    Pair("Cada día es una página nueva. Escribila con esfuerzo.", "Anónimo"),
    Pair("No hay mejor inversión que tu salud.", "Anónimo"),
    Pair("Levantá más peso. Levantá más vida.", "Anónimo"),
    Pair("La clave no es la intensidad. Es la continuidad.", "Anónimo"),
    Pair("Sé fiel a tu proceso.", "Anónimo"),
    Pair("Tu cuerpo es tu templo. Tratalo como tal.", "Anónimo"),
    Pair("Los campeones entrenan cuando nadie los ve.", "Anónimo"),
    Pair("Hacer lo difícil hoy hace la vida más fácil mañana.", "Anónimo"),
    Pair("No pidas que sea más fácil. Pedí ser más fuerte.", "Jim Rohn"),
    Pair("Sé obsesivo con tu progreso.", "Anónimo"),
    Pair("El cuerpo fuerte empieza con pensamientos fuertes.", "Anónimo"),
    Pair("Que tus acciones de hoy sean más grandes que tus palabras de ayer.", "Anónimo"),
    Pair("Nunca subestimes el poder de un entrenamiento consistente.", "Anónimo"),
    Pair("Sé más fuerte que tus disculpas.", "Anónimo"),
    Pair("Los resultados requieren tiempo. El tiempo requiere paciencia.", "Anónimo"),
    Pair("Cada entrenamiento completo es una promesa cumplida.", "Anónimo"),
    Pair("Sé el tipo de persona que termina lo que empieza.", "Anónimo"),
    Pair("El dolor de hoy es la fortaleza de mañana.", "Anónimo"),
    Pair("El que no trabaja duro, sueña despierto.", "Anónimo"),
    Pair("Transformate con cada repetición.", "Anónimo"),
    Pair("No necesitás ser el mejor del gym. Solo necesitás ser mejor que ayer.", "Anónimo"),
    Pair("La velocidad no importa si la dirección es correcta.", "Anónimo"),
    Pair("Hacé el trabajo. Los resultados seguirán.", "Anónimo"),
    Pair("Sé disciplinado en los días difíciles y los días fáciles se cuidarán solos.", "Anónimo"),
    Pair("El mejor momento para entrenar es ahora.", "Anónimo"),
    Pair("Cada kilo es una historia de esfuerzo y dedicación.", "Anónimo"),
    Pair("La superación personal no tiene techo.", "Anónimo"),
    Pair("Entrená con el corazón, no solo con el cuerpo.", "Anónimo"),
    Pair("Los grandes cambios empiezan con pequeñas decisiones consistentes.", "Anónimo"),
    Pair("Tu esfuerzo de hoy define tu físico de mañana.", "Anónimo"),
    Pair("Sé el atleta de tu propia historia.", "Anónimo"),
    Pair("No hay excusa lo suficientemente grande como para abandonar tu salud.", "Anónimo"),
    Pair("Cada entrenamiento construye no solo músculo, sino también carácter.", "Anónimo"),
    Pair("El movimiento es vida. La vida es movimiento.", "Anónimo"),
    Pair("Cuanto más duro entrenes, más fácil se vuelve la vida.", "Anónimo"),
    Pair("Sé constante. Los resultados llegarán.", "Anónimo"),
    Pair("La perseverancia es el combustible del éxito.", "Anónimo"),
    Pair("No dejés que un día malo te quite un buen entrenamiento.", "Anónimo"),
    Pair("El gym no discrimina. Acepta a todos los que se presentan.", "Anónimo"),
    Pair("Sé el arquitecto de tu propio cuerpo.", "Anónimo"),
    Pair("Un cuerpo activo es un cuerpo feliz.", "Anónimo"),
    Pair("El entrenamiento de hoy es el combustible de mañana.", "Anónimo"),
    Pair("Hacé que valga cada gota de sudor.", "Anónimo"),
    Pair("Los sueños sin esfuerzo son solo ilusiones.", "Anónimo"),
    Pair("No hay excusa válida cuando se trata de tu salud.", "Anónimo"),
    Pair("Sé más grande que tus obstáculos.", "Anónimo"),
    Pair("Cada paso en el gym es un paso hacia la mejor versión de vos.", "Anónimo"),
    Pair("Entrená hoy para ser invencible mañana.", "Anónimo"),
    Pair("El esfuerzo siempre supera al talento a largo plazo.", "Anónimo"),
    Pair("Sé un ejemplo de lo que podés lograr con disciplina.", "Anónimo"),
    Pair("No busques el camino fácil. Buscá el camino que te haga crecer.", "Anónimo"),
    Pair("Cada entrenamiento es una inversión en tu futuro.", "Anónimo"),
    Pair("Tu fortaleza interior se refleja en tu fortaleza exterior.", "Anónimo"),
    Pair("No esperes resultados sin esfuerzo.", "Anónimo"),
    Pair("Sé consistente aunque no veas cambios inmediatos.", "Anónimo"),
    Pair("El progreso es lento pero seguro si sos constante.", "Anónimo"),
    Pair("Transforma el esfuerzo en arte.", "Anónimo"),
    Pair("Cada sesión en el gym te hace más resiliente.", "Anónimo"),
    Pair("Sé imparable. Sé invencible. Sé vos.", "Anónimo"),
    Pair("No importa cuántas veces caigas. Importa cuántas veces te levantás.", "Anónimo"),
    Pair("El entrenamiento no es solo físico. Es mental.", "Anónimo"),
    Pair("Sé el tipo de persona que se supera cada día.", "Anónimo"),
    Pair("No hay límite para lo que podés lograr si no te rendís.", "Anónimo"),
    Pair("La disciplina crea libertad.", "Jocko Willink"),
    Pair("Sé fuerte cuando todo te pide que te rindas.", "Anónimo"),
    Pair("El sudor es el aroma del éxito.", "Anónimo"),
    Pair("Cada entrenamiento es una oportunidad de superarte.", "Anónimo"),
    Pair("No subestimes el poder del movimiento diario.", "Anónimo"),
    Pair("Sé más grande que tus excusas y más fuerte que tus miedos.", "Anónimo"),
    Pair("La determinación es lo que separa a los que sueñan de los que logran.", "Anónimo"),
    Pair("Hacé que tu esfuerzo hable por vos.", "Anónimo"),
    Pair("Sé el cambio que querés ver en tu vida.", "Mahatma Gandhi"),
    Pair("No hay meta imposible para quien no acepta el fracaso.", "Anónimo"),
    Pair("Cada rep que hacés en el gym es un no a la mediocridad.", "Anónimo"),
    Pair("La fortaleza no se hereda. Se construye.", "Anónimo"),
    Pair("Sé implacable con tu progreso.", "Anónimo"),
    Pair("El gimnasio es la escuela de la disciplina.", "Anónimo"),
    Pair("Cada entrenamiento te acerca al cuerpo que merecés.", "Anónimo"),
    Pair("Sé curioso, sé fuerte, sé imparable.", "Anónimo"),
    Pair("No te rindas en el momento más difícil. Es cuando más cerca estás.", "Anónimo"),
    Pair("Tu esfuerzo de hoy construye el camino de mañana.", "Anónimo"),
    Pair("Sé el mejor versión de vos mismo, todos los días.", "Anónimo"),
    Pair("La constancia es el arma secreta de los exitosos.", "Anónimo"),
    Pair("No busques comodidad. Buscá crecimiento.", "Anónimo"),
    Pair("Cada entrenamiento es un acto de amor hacia vos mismo.", "Anónimo"),
    Pair("Sé más fuerte que el dolor y más grande que el miedo.", "Anónimo"),
    Pair("El trabajo silencioso produce resultados ruidosos.", "Anónimo"),
    Pair("No importa cuántos tropiezos. Lo que importa es que seguís.", "Anónimo"),
    Pair("Sé la persona que va al gym cuando nadie lo ve.", "Anónimo"),
    Pair("Los hábitos saludables son la mejor herencia que podés darte.", "Anónimo"),
    Pair("Cada entrenamiento es un paso hacia la longevidad.", "Anónimo"),
    Pair("No dejes que el cansancio de hoy te robe la energía de mañana.", "Anónimo"),
    Pair("Sé disciplinado hoy para ser libre mañana.", "Anónimo"),
    Pair("El cuerpo que tenés es el resultado de las decisiones que tomaste.", "Anónimo"),
    Pair("Hacé del gym tu refugio y del esfuerzo tu hábito.", "Anónimo"),
    Pair("No hay transformación sin transpiración.", "Anónimo"),
    Pair("Sé el ejemplo viviente de que el esfuerzo funciona.", "Anónimo"),
    Pair("Cada entrenamiento que completás es una victoria que nadie te puede quitar.", "Anónimo"),
    Pair("No pares. El camino al éxito no tiene semáforos en rojo.", "Anónimo"),
    Pair("Sé ambicioso con tus metas y paciente con tus resultados.", "Anónimo"),
    Pair("El cuerpo sigue a la mente. Fortalecé la mente primero.", "Anónimo"),
    Pair("Cada día que entrenás es un día que ganás.", "Anónimo"),
    Pair("Sé más fuerte que ayer. Más sabio que hoy.", "Anónimo"),
    Pair("No hay recompensa sin riesgo. No hay músculo sin esfuerzo.", "Anónimo"),
    Pair("Hacé del movimiento tu filosofía de vida.", "Anónimo"),
    Pair("Sé el tipo de persona que no necesita motivación externa.", "Anónimo"),
    Pair("Cada entrenamiento es un depósito en tu cuenta de salud.", "Anónimo"),
    Pair("No busques excusas. Buscá soluciones.", "Anónimo"),
    Pair("Sé más fuerte que tus pensamientos limitantes.", "Anónimo"),
    Pair("El gym te enseña más sobre vos mismo que cualquier libro.", "Anónimo"),
    Pair("Cada vez que entrenas, le decís sí a la vida.", "Anónimo"),
    Pair("Sé fiel a tu proceso aunque los resultados tarden.", "Anónimo"),
    Pair("No hay nada más poderoso que un hábito bien construido.", "Anónimo"),
    Pair("Hacé que cada sesión cuente.", "Anónimo"),
    Pair("Sé el guerrero que el mundo necesita ver.", "Anónimo"),
    Pair("Cada entrenamiento es una declaración de amor a tu cuerpo.", "Anónimo"),
    Pair("No dejes que los días malos se conviertan en semanas malas.", "Anónimo"),
    Pair("Sé persistente. Los resultados llegan para los que no se rinden.", "Anónimo"),
    Pair("El entrenamiento es la forma más honesta de superación personal.", "Anónimo"),
    Pair("Cada rep que hacés te hace más resistente a la adversidad.", "Anónimo"),
    Pair("Sé más que tus limitaciones.", "Anónimo"),
    Pair("No hay excusa más grande que tu potencial.", "Anónimo"),
    Pair("Hacé del esfuerzo tu identidad.", "Anónimo"),
    Pair("Sé el tipo de persona que elige el gym sobre el sofá.", "Anónimo"),
    Pair("Cada entrenamiento es una página más en el libro de tu éxito.", "Anónimo"),
    Pair("No dejes que la pereza robe tu mejor versión.", "Anónimo"),
    Pair("Sé imparable en la búsqueda de tu mejor yo.", "Anónimo"),
    Pair("El entrenamiento constante es la clave del cambio duradero.", "Anónimo"),
    Pair("Cada día que entrenás, escribís una historia de superación.", "Anónimo"),
    Pair("Sé más grande que tus limitaciones mentales.", "Anónimo"),
    Pair("No hay mejor terapia que el sudor honesto.", "Anónimo"),
    Pair("Hacé que tu cuerpo sea un reflejo de tu dedicación.", "Anónimo"),
    Pair("Sé el tipo de persona que termina lo que empieza, siempre.", "Anónimo"),
    Pair("Cada entrenamiento te hace más capaz de enfrentar la vida.", "Anónimo"),
    Pair("No busques el aplauso. Buscá el progreso.", "Anónimo"),
    Pair("Sé disciplinado en la oscuridad para brillar en la luz.", "Anónimo"),
    Pair("El gym es donde las palabras se convierten en hechos.", "Anónimo"),
    Pair("Cada serie completada es una promesa que te cumplís.", "Anónimo"),
    Pair("Sé más fuerte que el ruido externo.", "Anónimo"),
    Pair("No importa lo que piensen los demás. Importa lo que hacés vos.", "Anónimo"),
    Pair("Hacé que tu esfuerzo sea tu legado.", "Anónimo"),
    Pair("Sé el tipo de persona que se levanta y entrena sin importar nada.", "Anónimo"),
    Pair("Cada entrenamiento es un tributo a tu potencial.", "Anónimo"),
    Pair("No dejes que el miedo al fracaso te impida intentarlo.", "Anónimo"),
    Pair("Sé constante. El tiempo hace el resto.", "Anónimo"),
    Pair("El esfuerzo honesto siempre tiene recompensa.", "Anónimo"),
    Pair("Cada día en el gym es una lección de vida.", "Anónimo"),
    Pair("Sé más fuerte que el día de ayer.", "Anónimo"),
    Pair("No hay límite para quien decide no tenerlo.", "Anónimo"),
)


@Composable
fun SplashScreen(onFinish: () -> Unit) {
    val hoy = remember {
        val cal = java.util.Calendar.getInstance()
        cal.get(java.util.Calendar.DAY_OF_YEAR)
    }
    val frase = remember { frases[hoy % frases.size] }

    var mostrarGym by remember { mutableStateOf(false) }
    var mostrarFrase by remember { mutableStateOf(false) }
    var mostrarAutor by remember { mutableStateOf(false) }

    LaunchedEffect(Unit) {
        delay(300)
        mostrarGym = true
        delay(600)
        mostrarFrase = true
        delay(800)
        mostrarAutor = true
        delay(5000)
        mostrarGym = false
        mostrarFrase = false
        mostrarAutor = false
        delay(800)
        onFinish()
    }

    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(
                Brush.linearGradient(
                    colors = listOf(Color(0xFF0D0D0D), Color(0xFF1A0A00))
                )
            ),
        contentAlignment = Alignment.Center
    ) {
        Column(
            horizontalAlignment = Alignment.CenterHorizontally,
            modifier = Modifier.padding(40.dp)
        ) {
            AnimatedVisibility(
                visible = mostrarGym,
                enter = fadeIn(tween(600)) + slideInVertically(tween(600)) { -20 },
                exit = fadeOut(tween(600))
            ) {
                Text(
                    text = "GYMOS",
                    fontSize = 13.sp,
                    color = Color(0xFFFF4500),
                    letterSpacing = 4.sp,
                    fontWeight = FontWeight.Bold
                )
            }

            Spacer(modifier = Modifier.height(24.dp))

            AnimatedVisibility(
                visible = mostrarFrase,
                enter = fadeIn(tween(800)) + slideInVertically(tween(800)) { 30 },
                exit = fadeOut(tween(600))
            ) {
                Text(
                    text = "\"${frase.first}\"",
                    fontSize = 22.sp,
                    fontWeight = FontWeight.ExtraBold,
                    color = Color.White,
                    textAlign = TextAlign.Center,
                    lineHeight = 32.sp
                )
            }

            Spacer(modifier = Modifier.height(16.dp))

            AnimatedVisibility(
                visible = mostrarAutor,
                enter = fadeIn(tween(600)),
                exit = fadeOut(tween(400))
            ) {
                Text(
                    text = "— ${frase.second}",
                    fontSize = 14.sp,
                    color = Color(0xFFAAAAAA),
                    fontStyle = FontStyle.Italic,
                    textAlign = TextAlign.Center
                )
            }
        }
    }
}